/* Database schema to keep the structure of entire database. */

  CREATE TABLE animals (
	ID int, 
	NAME varchar(100), 
	DATE_OF_BIRTH date, 
	ESCAPE_ATTEMPTS int, 
	NEUTERED boolean, 
	WEIGHT_KG decimal
    );


ALTER TABLE animals ADD SPECIES varchar(50);

CREATE TABLE OWNERS(
ID  SERIAL PRIMARY KEY,
FULL_NAME varchar(100),
AGE int
)

CREATE TABLE SPECIES(
ID  SERIAL PRIMARY KEY,
NAME varchar(100)
)

ALTER TABLE ANIMALS ADD PRIMARY KEY (ID)
ALTER TABLE ANIMALS DROP COLUMN SPECIES
ALTER TABLE ANIMALS ADD SPECIES_ID int 

ALTER TABLE ANIMALS ADD FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES (ID);

ALTER TABLE ANIMALS ADD OWNER_ID int 
ALTER TABLE ANIMALS ADD FOREIGN KEY (OWNER_ID) REFERENCES OWNERS (ID);

CREATE TABLE VETS (
ID SERIAL PRIMARY KEY,
NAME VARCHAR(100),
AGE INT,
DATE_OF_GRADUATION DATE
)

CREATE TABLE SPECIALIZATIONS (
SPECIES_ID INT,
VET_ID INT
)

CREATE TABLE VISITS (
ANIMAL_ID INT,
VET_ID INT,
DATE_OF_VISIT DATE
)

ALTER TABLE owners ADD COLUMN email VARCHAR(120);